Add better display of failure summary for github workflows. Change the URL from next to staging. Change AI assistant panel's close button loAdd better display of failure summary for github workflows.

diff --git a/.github/workflows/reusable-workflow.yml b/.github/workflows/reusable-workflow.yml
--- a/.github/workflows/reusable-workflow.yml
+++ b/.github/workflows/reusable-workflow.yml
@@ -114,3 +114,13 @@ jobs:
           name: error-screenshots-${{ matrix.browser }}-${{ github.run_id }}-${{ github.job }}-${{ github.step }}
           path: latest_logs/errors
           if-no-files-found: warn
+
+      - name: Display summary of failures
+        if: always()
+        run: |
+          echo "======SUMMARY OF FAILURES======="
+          if [ -f result.log ]; then
+             grep -A 5 "FAILED" result.log || echo "✅ All tests passed"
+          else
+              echo "result.log not found"
+          fi
