Add step to workflow to mkdir and have error.log

diff --git a/.github/workflows/reusable-workflow.yml b/.github/workflows/reusable-workflow.yml
--- a/.github/workflows/reusable-workflow.yml
+++ b/.github/workflows/reusable-workflow.yml
@@ -105,6 +105,10 @@ jobs:
             --self-contained-html \
            --browser-name=chrome
 
+      - name: Run tests and capture output
+        run: |
+          mkdir -p latest_logs/errors
+          pytest tests/ > latest_logs/errors/result.log
 
       # Upload test artifacts (screenshots) if failure
       - name: Upload test artifacts (screenshots)
@@ -119,8 +123,8 @@ jobs:
         if: always()
         run: |
           echo "======SUMMARY OF FAILURES======="
-          if [ -f result.log ]; then
-             grep -A 5 "FAILED" result.log || echo "✅ All tests passed"
+          if [ -f latest_logs/errors/result.log ]; then
+             grep -A 5 "FAILED" latest_logs/errors/result.log || echo "✅ All tests passed"
           else
-              echo "result.log not found"
+             echo "❌ latest_logs/errors/result.log not found"
           fi
