Correct uploading of the screenshots location to the rest of the steps

diff --git a/.github/workflows/selenium-tests.yml b/.github/workflows/selenium-tests.yml
--- a/.github/workflows/selenium-tests.yml
+++ b/.github/workflows/selenium-tests.yml
@@ -72,7 +72,7 @@ jobs:
           google-chrome --version
 
       - name: Create Logs Directory
-        run: mkdir -p latest_logs
+        run: mkdir -p latest_logs/errors
 
       - name: Debug Environment Variables
         run: echo $BASE_URL
@@ -93,22 +93,19 @@ jobs:
           name: test-report-production-${{ matrix.browser }}
           path: latest_logs/
 
-      - name: Upload error screenshots
+      - name: Debug Error Directory
         if: failure()
         run: |
-          if [ -d "latest_logs/screenshots/" ]; then
-            echo "Screenshots directory found."
-          else
-            echo "No screenshots to upload."
-            exit 0
-          fi
+          echo "Contents of latest_logs/errors:"
+          ls -la latest_logs/errors || echo "No files in the directory"
 
       - name: Upload test artifacts (screenshots)
         if: failure()
         uses: actions/upload-artifact@v4
         with:
           name: error-screenshots
-          path: latest_logs/screenshots/
+          path: latest_logs/errors
+          if-no-files-found: warn
 
       - name: Notify slack on success
         if: success()
@@ -158,7 +155,7 @@ jobs:
         run: google-chrome --version
 
       - name: Create Logs Directory
-        run: mkdir -p latest_logs
+        run: mkdir -p latest_logs/errors
 
       - name: Run tests for Sauce Labs
         env:
@@ -179,22 +176,19 @@ jobs:
           name: test-report-sauce-labs-${{ matrix.browser }}
           path: latest_logs/
 
-      - name: Upload error screenshots
+      - name: Debug Error Directory
         if: failure()
         run: |
-          if [ -d "latest_logs/screenshots/" ]; then
-            echo "Screenshots directory found."
-          else
-            echo "No screenshots to upload."
-            exit 0
-          fi
+          echo "Contents of latest_logs/errors:"
+          ls -la latest_logs/errors || echo "No files in the directory"
 
       - name: Upload test artifacts (screenshots)
         if: failure()
         uses: actions/upload-artifact@v4
         with:
           name: error-screenshots
-          path: latest_logs/screenshots/
+          path: latest_logs/errors
+          if-no-files-found: warn
 
   test-staging:
     needs: test-sauce-labs
